# Generated by Django 4.2.10 on 2024-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vouchermaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='pin',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
