# Generated by Django 4.2.10 on 2024-02-25 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('vouchermaker', '0002_alter_voucher_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='name',
        ),
    ]
