# Generated by Django 4.2.10 on 2024-02-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vouchermaker', '0003_remove_voucher_email_remove_voucher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expires_at',
            field=models.DateField(null=True),
        ),
    ]
